name: Setup CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run npm install
        run: npm i
      - name: Run prettier check
        run: npm run check-format
      - name: Run eslint check
        run: npm run lint:fix
      - name: Run typescript check
        run: npm run check-types
      - name: Run tests
        run: npm run test-prod
      - name: Build project
        run: npm run build

    # - name: Build and Push to docker
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
